### ISSUE TITLE
README.md 中的 Microsoft Teams 連結無效

### ISSUE THREAD

**Issue by BBleae** [ChinatsuSuzuki6/Transgender-Support-Coalition#4]
不論我使用個人帳號還是工作或學校帳號都無法加入
![image](https://github.com/ChinatsuSuzuki6/Transgender-Support-Coalition/assets/13044102/f5a23ae6-3095-4bd7-aa88-d06fb8399719)

**Comment by ChinatsuSuzuki6** [comment]
嗯，知道了

**Comment by ChinatsuSuzuki6** [comment]
問題已解決，我們去除了鏈接~~~~
